name: Labubu Watcher Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and Chromium
        run: PUPPETEER_PRODUCT=chrome npm install

      - name: Create .env file from secrets
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env

      - name: Run monitor job
        run: npm run run:all